Element.create(
                     name: "Hydrogen",
                   symbol: "H",
            atomic_number: 1,
            atomic_weight: 1.00794,
                  density: "0.0708 (@ -253degC)",
            melting_point: -259.14,
            boiling_point: -252.87,
            atomic_radius: 79,
          covalent_radius: "32",
             ionic_radius: nil,
          specific_volume: 14.1,
            specific_heat: "14.267 (H-H)",
              heat_fusion: "0.117 (H-H)",
         heat_evaporation: "0.904 (H-H)",
     thermal_conductivity: "0.1815",
pauling_electronegativity: 2.2,
  first_ionisation_energy: "1311.3",
         oxidation_states: "1 -1",
 electronic_configuration: "1s¹",
                  lattice: "HEX",
         lattice_constant: 3.75,
                 category: "nonmetals",
                   number: 1
)
Element.create(
                     name: "Carbon",
                   symbol: "C",
            atomic_number: 6,
            atomic_weight: 12.011,
                  density: "2.25 (graphite)",
            melting_point: 3546.85,
            boiling_point: 4826.85,
            atomic_radius: 91,
          covalent_radius: "77",
             ionic_radius: nil,
          specific_volume: 5.3,
            specific_heat: "0.711",
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: "1.59",
pauling_electronegativity: 2.55,
  first_ionisation_energy: "1085.7",
         oxidation_states: "4 2 -4",
 electronic_configuration: "[He]2s²2p²",
                  lattice: "DIA",
         lattice_constant: 3.57,
                 category: "nonmetals",
                   number: 6
)
Element.create(
                     name: "Nitrogen",
                   symbol: "N",
            atomic_number: 7,
            atomic_weight: 14.00674,
                  density: "0.808 (@ -195.8degC)",
            melting_point: -209.86,
            boiling_point: -195.75,
            atomic_radius: 92,
          covalent_radius: "75",
             ionic_radius: nil,
          specific_volume: 17.3,
            specific_heat: "1.042 (N-N)",
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: "0.026",
pauling_electronegativity: 3.04,
  first_ionisation_energy: "1401.5",
         oxidation_states: "5 4 3 2 -3",
 electronic_configuration: "[He]2s²2p³",
                  lattice: "HEX",
         lattice_constant: 4.039,
                 category: "nonmetals",
                   number: 7
)
Element.create(
                     name: "Lithium",
                   symbol: "Li",
            atomic_number: 3,
            atomic_weight: 6.941,
                  density: "0.534",
            melting_point: 280.54,
            boiling_point: 845,
            atomic_radius: 155,
          covalent_radius: "163",
             ionic_radius: nil,
          specific_volume: 13.1,
            specific_heat: "3.489",
              heat_fusion: "2.89",
         heat_evaporation: "148",
     thermal_conductivity: "84.8",
pauling_electronegativity: 0.98,
  first_ionisation_energy: "519.9",
         oxidation_states: "1",
 electronic_configuration: "[He]2s¹",
                  lattice: "BCC",
         lattice_constant: 3.49,
                 category: "alkali metals",
                   number: 3
)
Element.create(
                     name: "Sodium",
                   symbol: "Na",
            atomic_number: 11,
            atomic_weight: 22.989768,
                  density: "0.971",
            melting_point: 97.81,
            boiling_point: 882.95,
            atomic_radius: 190,
          covalent_radius: "154",
             ionic_radius: nil,
          specific_volume: 23.7,
            specific_heat: "1.222",
              heat_fusion: "2.64",
         heat_evaporation: "97.9",
     thermal_conductivity: "142",
pauling_electronegativity: 0.93,
  first_ionisation_energy: "495.6",
         oxidation_states: "1",
 electronic_configuration: "[Ne]3s¹",
                  lattice: "BCC",
         lattice_constant: 4.23,
                 category: "alkali metals",
                   number: 11
)
Element.create(
                     name: "Potassium",
                   symbol: "K",
            atomic_number: 19,
            atomic_weight: 39.0983,
                  density: "0.856",
            melting_point: 63.65,
            boiling_point: 773.85,
            atomic_radius: 235,
          covalent_radius: "203",
             ionic_radius: nil,
          specific_volume: 45.3,
            specific_heat: "0.753",
              heat_fusion: "102.5",
         heat_evaporation: "2.33",
     thermal_conductivity: "79",
pauling_electronegativity: 0.82,
  first_ionisation_energy: "418.5",
         oxidation_states: "1",
 electronic_configuration: "[Ar]4s¹",
                  lattice: "BCC",
         lattice_constant: 5.23,
                 category: "alkali metals",
                   number: 19
)
Element.create(
                     name: "Rubidium",
                   symbol: "Rb",
            atomic_number: 37,
            atomic_weight: 85.4678,
                  density: "1.532",
            melting_point: 39.05,
            boiling_point: 687.85,
            atomic_radius: 248,
          covalent_radius: "216",
             ionic_radius: nil,
          specific_volume: 55.9,
            specific_heat: "0.36",
              heat_fusion: "2.2",
         heat_evaporation: "75.8",
     thermal_conductivity: "58.2",
pauling_electronegativity: 0.82,
  first_ionisation_energy: "402.8",
         oxidation_states: "1",
 electronic_configuration: "[Kr]5s¹",
                  lattice: "BCC",
         lattice_constant: 5.59,
                 category: "alkali metals",
                   number: 37
)
Element.create(
                     name: "Beryllium",
                   symbol: "Be",
            atomic_number: 4,
            atomic_weight: 9.01218,
                  density: "1.848",
            melting_point: 1277.85,
            boiling_point: 2969.85,
            atomic_radius: 112,
          covalent_radius: "90",
             ionic_radius: nil,
          specific_volume: 5,
            specific_heat: "1.824",
              heat_fusion: "12.21",
         heat_evaporation: "309",
     thermal_conductivity: "201",
pauling_electronegativity: 1.57,
  first_ionisation_energy: "898.8",
         oxidation_states: "2",
 electronic_configuration: "[He]2s²",
                  lattice: "HEX",
         lattice_constant: 2.29,
                 category: "alkaline metals",
                   number: 4
)
Element.create(
                     name: "Magnesium",
                   symbol: "Mg",
            atomic_number: 12,
            atomic_weight: 24.305,
                  density: "1.738",
            melting_point: 648.85,
            boiling_point: 1089.85,
            atomic_radius: 160,
          covalent_radius: "136",
             ionic_radius: nil,
          specific_volume: 14,
            specific_heat: "1.025",
              heat_fusion: "9.2",
         heat_evaporation: "131.8",
     thermal_conductivity: "156",
pauling_electronegativity: 1.31,
  first_ionisation_energy: "737.3",
         oxidation_states: "2",
 electronic_configuration: "[Ne]3s²",
                  lattice: "HEX",
         lattice_constant: 3.21,
                 category: "alkaline metals",
                   number: 12
)
Element.create(
                     name: "Calcium",
                   symbol: "Ca",
            atomic_number: 20,
            atomic_weight: 40.078,
                  density: "1.55",
            melting_point: 838.85,
            boiling_point: 1483.85,
            atomic_radius: 197,
          covalent_radius: "174",
             ionic_radius: nil,
          specific_volume: 29.9,
            specific_heat: "0.653",
              heat_fusion: "9.2",
         heat_evaporation: "153.6",
     thermal_conductivity: "<201>",
pauling_electronegativity: 1,
  first_ionisation_energy: "589.4",
         oxidation_states: "2",
 electronic_configuration: "[Ar]4s²",
                  lattice: "FCC",
         lattice_constant: 5.58,
                 category: "alkaline metals",
                   number: 20
)
Element.create(
                     name: "Strontium",
                   symbol: "Sr",
            atomic_number: 38,
            atomic_weight: 87.62,
                  density: "2.54",
            melting_point: 768.85,
            boiling_point: 1383.85,
            atomic_radius: 215,
          covalent_radius: "191",
             ionic_radius: nil,
          specific_volume: 33.7,
            specific_heat: "0.301",
              heat_fusion: "9.2",
         heat_evaporation: "144",
     thermal_conductivity: "<35.4>",
pauling_electronegativity: 0.95,
  first_ionisation_energy: "549",
         oxidation_states: "2",
 electronic_configuration: "[Kr]5s²",
                  lattice: "FCC",
         lattice_constant: 6.08,
                 category: "alkaline metals",
                   number: 38
)
Element.create(
                     name: "Aluminum",
                   symbol: "Al",
            atomic_number: 13,
            atomic_weight: 26.981539,
                  density: "2.6989",
            melting_point: 660.35,
            boiling_point: 2466.85,
            atomic_radius: 143,
          covalent_radius: "118",
             ionic_radius: nil,
          specific_volume: 10,
            specific_heat: "0.9",
              heat_fusion: "10.75",
         heat_evaporation: "284.1",
     thermal_conductivity: "237",
pauling_electronegativity: 1.61,
  first_ionisation_energy: "577.2",
         oxidation_states: "3",
 electronic_configuration: "[Ne]3s²3p¹",
                  lattice: "FCC",
         lattice_constant: 4.05,
                 category: "other metals",
                   number: 13
)
Element.create(
                     name: "Gallium",
                   symbol: "Ga",
            atomic_number: 31,
            atomic_weight: 69.723,
                  density: "5.91",
            melting_point: 29.78,
            boiling_point: 2402.85,
            atomic_radius: 141,
          covalent_radius: "126",
             ionic_radius: nil,
          specific_volume: 11.8,
            specific_heat: "0.372",
              heat_fusion: "5.59",
         heat_evaporation: "270.3",
     thermal_conductivity: "28.1",
pauling_electronegativity: 1.81,
  first_ionisation_energy: "578.7",
         oxidation_states: "3",
 electronic_configuration: "[Ar]3d¹4s²4p¹",
                  lattice: "ORC",
         lattice_constant: 4.51,
                 category: "other metals",
                   number: 31
)
Element.create(
                     name: "Boron",
                   symbol: "B",
            atomic_number: 5,
            atomic_weight: 10.811,
                  density: "2.34",
            melting_point: 2299.85,
            boiling_point: 3657.85,
            atomic_radius: 98,
          covalent_radius: "82",
             ionic_radius: nil,
          specific_volume: 4.6,
            specific_heat: "1.025",
              heat_fusion: "23.6",
         heat_evaporation: "504.5",
     thermal_conductivity: "27.4",
pauling_electronegativity: 2.04,
  first_ionisation_energy: "800.2",
         oxidation_states: "3",
 electronic_configuration: "[He]2s²2p¹",
                  lattice: "TET",
         lattice_constant: 8.73,
                 category: "metalloids",
                   number: 5
)
Element.create(
                     name: "Silicon",
                   symbol: "Si",
            atomic_number: 14,
            atomic_weight: 28.0855,
                  density: "2.33",
            melting_point: 1409.85,
            boiling_point: 2354.85,
            atomic_radius: 132,
          covalent_radius: "111",
             ionic_radius: nil,
          specific_volume: 12.1,
            specific_heat: "0.703",
              heat_fusion: "50.6",
         heat_evaporation: "383",
     thermal_conductivity: "149",
pauling_electronegativity: 1.9,
  first_ionisation_energy: "786",
         oxidation_states: "4 -4",
 electronic_configuration: "[Ne]3s²3p²",
                  lattice: "DIA",
         lattice_constant: 5.43,
                 category: "metalloids",
                   number: 14
)
Element.create(
                     name: "Barium",
                   symbol: "Ba",
            atomic_number: 56,
            atomic_weight: 137.327,
                  density: "3.5",
            melting_point: 728.85,
            boiling_point: 1636.85,
            atomic_radius: 222,
          covalent_radius: "198",
             ionic_radius: nil,
          specific_volume: 39,
            specific_heat: "0.192",
              heat_fusion: "7.66",
         heat_evaporation: "142",
     thermal_conductivity: "<18.4>",
pauling_electronegativity: 0.89,
  first_ionisation_energy: "502.5",
         oxidation_states: "2",
 electronic_configuration: "[Xe]6s²",
                  lattice: "BCC",
         lattice_constant: 5.02,
                 category: "alkaline metals",
                   number: 56
)
Element.create(
                     name: "Radium",
                   symbol: "Ra",
            atomic_number: 88,
            atomic_weight: 226.0254,
                  density: "<5.5>",
            melting_point: 699.85,
            boiling_point: 1139.85,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 45,
            specific_heat: "0.12",
              heat_fusion: "-9.6",
         heat_evaporation: "-113",
     thermal_conductivity: "<18.6>",
pauling_electronegativity: 0.9,
  first_ionisation_energy: "509",
         oxidation_states: "2",
 electronic_configuration: "[Rn]7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "alkaline metals",
                   number: 88
)
Element.create(
                     name: "Indium",
                   symbol: "In",
            atomic_number: 49,
            atomic_weight: 114.818,
                  density: "7.31",
            melting_point: 156.17,
            boiling_point: 2079.85,
            atomic_radius: 166,
          covalent_radius: "144",
             ionic_radius: nil,
          specific_volume: 15.7,
            specific_heat: "0.234",
              heat_fusion: "3.24",
         heat_evaporation: "225.1",
     thermal_conductivity: "81.8",
pauling_electronegativity: 1.78,
  first_ionisation_energy: "558",
         oxidation_states: "3",
 electronic_configuration: "[Kr]4d5s²5p¹",
                  lattice: "TET",
         lattice_constant: 4.59,
                 category: "other metals",
                   number: 49
)
Element.create(
                     name: "Antimony",
                   symbol: "Sb",
            atomic_number: 51,
            atomic_weight: 121.76,
                  density: "6.691",
            melting_point: 630.75,
            boiling_point: 1634.85,
            atomic_radius: 159,
          covalent_radius: "140",
             ionic_radius: nil,
          specific_volume: 18.4,
            specific_heat: "0.205",
              heat_fusion: "20.08",
         heat_evaporation: "195.2",
     thermal_conductivity: "24.43",
pauling_electronegativity: 2.05,
  first_ionisation_energy: "833.3",
         oxidation_states: "5 3 -2",
 electronic_configuration: "[Kr]4d5s²5p³",
                  lattice: "RHL",
         lattice_constant: 4.51,
                 category: "metalloids",
                   number: 51
)
Element.create(
                     name: "Tellurium",
                   symbol: "Te",
            atomic_number: 52,
            atomic_weight: 127.6,
                  density: "6.24",
            melting_point: 449.55,
            boiling_point: 989.85,
            atomic_radius: 160,
          covalent_radius: "136",
             ionic_radius: nil,
          specific_volume: 20.5,
            specific_heat: "0.201",
              heat_fusion: "17.91",
         heat_evaporation: "49.8",
     thermal_conductivity: "14.3",
pauling_electronegativity: 2.1,
  first_ionisation_energy: "869",
         oxidation_states: "6 4 2",
 electronic_configuration: "[Kr]4d5s²5p",
                  lattice: "HEX",
         lattice_constant: 4.45,
                 category: "metalloids",
                   number: 52
)
Element.create(
                     name: "Polonium",
                   symbol: "Po",
            atomic_number: 84,
            atomic_weight: 208.9824,
                  density: "9.32",
            melting_point: 253.85,
            boiling_point: 961.85,
            atomic_radius: 176,
          covalent_radius: "146",
             ionic_radius: nil,
          specific_volume: 22.7,
            specific_heat: "0.125",
              heat_fusion: "-10",
         heat_evaporation: "-102.9",
     thermal_conductivity: nil,
pauling_electronegativity: 2,
  first_ionisation_energy: "813.1",
         oxidation_states: "6 4 2",
 electronic_configuration: "[Xe]4f¹5d¹6s²6p",
                  lattice: "SC",
         lattice_constant: 3.35,
                 category: "metalloids",
                   number: 84
)
Element.create(
                     name: "Iodine",
                   symbol: "I",
            atomic_number: 53,
            atomic_weight: 126.90447,
                  density: "4.93",
            melting_point: 113.55,
            boiling_point: 184.35,
            atomic_radius: nil,
          covalent_radius: "133",
             ionic_radius: nil,
          specific_volume: 25.7,
            specific_heat: "0.427 (I-I)",
              heat_fusion: "15.52 (I-I)",
         heat_evaporation: "41.95 (I-I)",
     thermal_conductivity: "<0.45>",
pauling_electronegativity: 2.66,
  first_ionisation_energy: "1008.3",
         oxidation_states: "7 5 1 -1",
 electronic_configuration: "[Kr]4d5s²5p",
                  lattice: "ORC",
         lattice_constant: 7.72,
                 category: "halogens",
                   number: 53
)
Element.create(
                     name: "Astatine",
                   symbol: "At",
            atomic_number: 85,
            atomic_weight: 209.9871,
                  density: nil,
            melting_point: 301.85,
            boiling_point: 336.85,
            atomic_radius: nil,
          covalent_radius: "<145>",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 2.2,
  first_ionisation_energy: "916.3",
         oxidation_states: "7 5 3 1 -1",
 electronic_configuration: "[Xe]4f¹5d¹6s²6p",
                  lattice: nil,
         lattice_constant: nil,
                 category: "halogens",
                   number: 85
)
Element.create(
                     name: "Xenon",
                   symbol: "Xe",
            atomic_number: 54,
            atomic_weight: 131.29,
                  density: "3.52 (@ -109degC)",
            melting_point: -111.85,
            boiling_point: -107.05,
            atomic_radius: nil,
          covalent_radius: "131",
             ionic_radius: nil,
          specific_volume: 42.9,
            specific_heat: "0.158",
              heat_fusion: nil,
         heat_evaporation: "12.65",
     thermal_conductivity: "0.0057",
pauling_electronegativity: 0,
  first_ionisation_energy: "1170",
         oxidation_states: "7",
 electronic_configuration: "[Kr]4d5s²5p",
                  lattice: "FCC",
         lattice_constant: 6.2,
                 category: "noble gases",
                   number: 54
)
Element.create(
                     name: "Radon",
                   symbol: "Rn",
            atomic_number: 86,
            atomic_weight: 222.0176,
                  density: "4.4 (@ -62degC)",
            melting_point: -71.15,
            boiling_point: -61.75,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: "0.094",
              heat_fusion: nil,
         heat_evaporation: "18.1",
     thermal_conductivity: "0.0036",
pauling_electronegativity: nil,
  first_ionisation_energy: "1036.5",
         oxidation_states: nil,
 electronic_configuration: "[Xe]4f¹5d¹6s²6p",
                  lattice: "FCC",
         lattice_constant: nil,
                 category: "noble gases",
                   number: 86
)
Element.create(
                     name: "Lanthanum",
                   symbol: "La",
            atomic_number: 57,
            atomic_weight: 138.9055,
                  density: "6.15",
            melting_point: 920.85,
            boiling_point: 3456.85,
            atomic_radius: 187,
          covalent_radius: "169",
             ionic_radius: nil,
          specific_volume: 22.5,
            specific_heat: "0.197",
              heat_fusion: "8.5",
         heat_evaporation: "402",
     thermal_conductivity: "13.4",
pauling_electronegativity: 1.1,
  first_ionisation_energy: "541.1",
         oxidation_states: "3",
 electronic_configuration: "[Xe]6d¹6s²",
                  lattice: "HEX",
         lattice_constant: 3.75,
                 category: "lanthanides",
                   number: 57
)
Element.create(
                     name: "Cerium",
                   symbol: "Ce",
            atomic_number: 58,
            atomic_weight: 140.115,
                  density: "6.757",
            melting_point: 798.85,
            boiling_point: 3425.85,
            atomic_radius: 181,
          covalent_radius: "165",
             ionic_radius: nil,
          specific_volume: 21,
            specific_heat: "0.205",
              heat_fusion: "5.2",
         heat_evaporation: "398",
     thermal_conductivity: "11.3",
pauling_electronegativity: 1.12,
  first_ionisation_energy: "540.1",
         oxidation_states: "4 3",
 electronic_configuration: "[Xe]4f¹5d¹6s²",
                  lattice: "FCC",
         lattice_constant: 5.16,
                 category: "lanthanides",
                   number: 58
)
Element.create(
                     name: "Praseodymium",
                   symbol: "Pr",
            atomic_number: 59,
            atomic_weight: 140.90765,
                  density: "6.773",
            melting_point: 930.85,
            boiling_point: 3511.85,
            atomic_radius: 182,
          covalent_radius: "165",
             ionic_radius: nil,
          specific_volume: 20.8,
            specific_heat: "0.192",
              heat_fusion: "11.3",
         heat_evaporation: "331",
     thermal_conductivity: "12.5",
pauling_electronegativity: 1.13,
  first_ionisation_energy: "526.6",
         oxidation_states: "4 3",
 electronic_configuration: "[Xe]4f³5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.67,
                 category: "lanthanides",
                   number: 59
)
Element.create(
                     name: "Neodymium",
                   symbol: "Nd",
            atomic_number: 60,
            atomic_weight: 144.24,
                  density: "7.007",
            melting_point: 1020.85,
            boiling_point: 3067.85,
            atomic_radius: 182,
          covalent_radius: "184",
             ionic_radius: nil,
          specific_volume: 20.6,
            specific_heat: "0.205",
              heat_fusion: "7.1",
         heat_evaporation: "289",
     thermal_conductivity: "<16.5>",
pauling_electronegativity: 1.14,
  first_ionisation_energy: "531.5",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.66,
                 category: "lanthanides",
                   number: 60
)
Element.create(
                     name: "Actinium",
                   symbol: "Ac",
            atomic_number: 89,
            atomic_weight: 227.0278,
                  density: nil,
            melting_point: 1046.85,
            boiling_point: 3196.85,
            atomic_radius: 188,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 22.54,
            specific_heat: nil,
              heat_fusion: "-10.5",
         heat_evaporation: "-292.9",
     thermal_conductivity: nil,
pauling_electronegativity: 1.1,
  first_ionisation_energy: "665.5",
         oxidation_states: "3",
 electronic_configuration: "[Rn]6d¹7s²",
                  lattice: "FCC",
         lattice_constant: 5.31,
                 category: "actinides",
                   number: 89
)
Element.create(
                     name: "Thorium",
                   symbol: "Th",
            atomic_number: 90,
            atomic_weight: 232.0381,
                  density: "11.78",
            melting_point: 1754.85,
            boiling_point: 4786.85,
            atomic_radius: 180,
          covalent_radius: "165",
             ionic_radius: nil,
          specific_volume: 19.8,
            specific_heat: "0.113",
              heat_fusion: "16.11",
         heat_evaporation: "513.7",
     thermal_conductivity: "<54>",
pauling_electronegativity: 1.3,
  first_ionisation_energy: "670.4",
         oxidation_states: "4",
 electronic_configuration: "[Rn]5f6d¹7s²",
                  lattice: "FCC",
         lattice_constant: 5.08,
                 category: "actinides",
                   number: 90
)
Element.create(
                     name: "Protactinium",
                   symbol: "Pa",
            atomic_number: 91,
            atomic_weight: 231.03588,
                  density: "15.37",
            melting_point: 1839.85,
            boiling_point: 4026.85,
            atomic_radius: 161,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 15,
            specific_heat: "0.121",
              heat_fusion: "16.7",
         heat_evaporation: "481.2",
     thermal_conductivity: nil,
pauling_electronegativity: 1.5,
  first_ionisation_energy: "nil",
         oxidation_states: "5 4",
 electronic_configuration: "[Rn]5f²6d¹7s²",
                  lattice: "TET",
         lattice_constant: 3.92,
                 category: "actinides",
                   number: 91
)
Element.create(
                     name: "Uranium",
                   symbol: "U",
            atomic_number: 92,
            atomic_weight: 238.0289,
                  density: "19.05",
            melting_point: 1132.35,
            boiling_point: 3744.85,
            atomic_radius: 138,
          covalent_radius: "142",
             ionic_radius: nil,
          specific_volume: 12.5,
            specific_heat: "0.115",
              heat_fusion: "12.6",
         heat_evaporation: "417",
     thermal_conductivity: "27.5",
pauling_electronegativity: 1.38,
  first_ionisation_energy: "686.4",
         oxidation_states: "6 5 4 3",
 electronic_configuration: "[Rn]5f³6d¹7s²",
                  lattice: "ORC",
         lattice_constant: 2.85,
                 category: "actinides",
                   number: 92
)
Element.create(
                     name: "Bohrium",
                   symbol: "Bh",
            atomic_number: 107,
            atomic_weight: 264,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 107
)
Element.create(
                     name: "Oxygen",
                   symbol: "O",
            atomic_number: 8,
            atomic_weight: 15.9994,
                  density: "1.149 (@ -183degC)",
            melting_point: -218.35,
            boiling_point: -182.96,
            atomic_radius: nil,
          covalent_radius: "73",
             ionic_radius: nil,
          specific_volume: 14,
            specific_heat: "0.916 (O-O)",
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: "0.027",
pauling_electronegativity: 3.44,
  first_ionisation_energy: "1313.1",
         oxidation_states: "-2 -1",
 electronic_configuration: "[He]2s²2p",
                  lattice: "CUB",
         lattice_constant: 6.83,
                 category: "nonmetals",
                   number: 8
)
Element.create(
                     name: "Phosphorus",
                   symbol: "P",
            atomic_number: 15,
            atomic_weight: 30.973762,
                  density: "1.82 (white phosphorus)",
            melting_point: 44.15,
            boiling_point: 279.85,
            atomic_radius: 128,
          covalent_radius: "106",
             ionic_radius: nil,
          specific_volume: 17,
            specific_heat: "0.757",
              heat_fusion: "2.51",
         heat_evaporation: "49.8",
     thermal_conductivity: "<0.236>",
pauling_electronegativity: 2.19,
  first_ionisation_energy: "1011.2",
         oxidation_states: "5 3 -3",
 electronic_configuration: "[Ne]3s²3p³",
                  lattice: "CUB",
         lattice_constant: 7.17,
                 category: "nonmetals",
                   number: 15
)
Element.create(
                     name: "Sulfur",
                   symbol: "S",
            atomic_number: 16,
            atomic_weight: 32.066,
                  density: "2.07",
            melting_point: 112.85,
            boiling_point: 444.674,
            atomic_radius: 127,
          covalent_radius: "102",
             ionic_radius: nil,
          specific_volume: 15.5,
            specific_heat: "0.732",
              heat_fusion: "1.23",
         heat_evaporation: "10.5",
     thermal_conductivity: "0.27",
pauling_electronegativity: 2.58,
  first_ionisation_energy: "999",
         oxidation_states: "6 4 2 -2",
 electronic_configuration: "[Ne]3s²3p",
                  lattice: "ORC",
         lattice_constant: 10.47,
                 category: "nonmetals",
                   number: 16
)
Element.create(
                     name: "Selenium",
                   symbol: "Se",
            atomic_number: 34,
            atomic_weight: 78.96,
                  density: "4.79",
            melting_point: 216.85,
            boiling_point: 684.95,
            atomic_radius: 140,
          covalent_radius: "116",
             ionic_radius: nil,
          specific_volume: 16.5,
            specific_heat: "0.321 (Se-Se)",
              heat_fusion: "5.23",
         heat_evaporation: "59.7",
     thermal_conductivity: "0.52",
pauling_electronegativity: 2.55,
  first_ionisation_energy: "940.4",
         oxidation_states: "6 4 -2",
 electronic_configuration: "[Ar]3d¹4s²4p",
                  lattice: "HEX",
         lattice_constant: 4.36,
                 category: "nonmetals",
                   number: 34
)
Element.create(
                     name: "Cesium",
                   symbol: "Cs",
            atomic_number: 55,
            atomic_weight: 132.90543,
                  density: "1.873",
            melting_point: 28.45,
            boiling_point: 678.45,
            atomic_radius: 267,
          covalent_radius: "235",
             ionic_radius: nil,
          specific_volume: 70,
            specific_heat: "0.241",
              heat_fusion: "2.09",
         heat_evaporation: "68.3",
     thermal_conductivity: "35.9",
pauling_electronegativity: 0.79,
  first_ionisation_energy: "375.5",
         oxidation_states: "1",
 electronic_configuration: "[Xe]6s¹",
                  lattice: "BCC",
         lattice_constant: 6.05,
                 category: "alkali metals",
                   number: 55
)
Element.create(
                     name: "Germanium",
                   symbol: "Ge",
            atomic_number: 32,
            atomic_weight: 72.61,
                  density: "5.323",
            melting_point: 937.45,
            boiling_point: 2829.85,
            atomic_radius: 137,
          covalent_radius: "122",
             ionic_radius: nil,
          specific_volume: 13.6,
            specific_heat: "0.322",
              heat_fusion: "36.8",
         heat_evaporation: "328",
     thermal_conductivity: "60.2",
pauling_electronegativity: 2.01,
  first_ionisation_energy: "760",
         oxidation_states: "4",
 electronic_configuration: "[Ar]3d¹4s²4p²",
                  lattice: "DIA",
         lattice_constant: 5.66,
                 category: "metalloids",
                   number: 32
)
Element.create(
                     name: "Arsenic",
                   symbol: "As",
            atomic_number: 33,
            atomic_weight: 74.92159,
                  density: "5.73 (grey arsenic)",
            melting_point: 816.85,
            boiling_point: 602.85,
            atomic_radius: 139,
          covalent_radius: "120",
             ionic_radius: nil,
          specific_volume: 13.1,
            specific_heat: "0.328",
              heat_fusion: nil,
         heat_evaporation: "32.4",
     thermal_conductivity: "<50.2>",
pauling_electronegativity: 2.18,
  first_ionisation_energy: "946.2",
         oxidation_states: "5 3 -2",
 electronic_configuration: "[Ar]3d¹4s²4p³",
                  lattice: "RHL",
         lattice_constant: 4.13,
                 category: "metalloids",
                   number: 33
)
Element.create(
                     name: "Fluorine",
                   symbol: "F",
            atomic_number: 9,
            atomic_weight: 18.998403,
                  density: "1.108 (@ -189degC)",
            melting_point: -219.62,
            boiling_point: -188.14,
            atomic_radius: nil,
          covalent_radius: "72",
             ionic_radius: nil,
          specific_volume: 17.1,
            specific_heat: "0.824 (F-F)",
              heat_fusion: "0.51 (F-F)",
         heat_evaporation: "6.54 (F-F)",
     thermal_conductivity: "0.028",
pauling_electronegativity: 3.98,
  first_ionisation_energy: "1680",
         oxidation_states: "-1",
 electronic_configuration: "[He]2s²2p",
                  lattice: "MCL",
         lattice_constant: nil,
                 category: "halogens",
                   number: 9
)
Element.create(
                     name: "Chlorine",
                   symbol: "Cl",
            atomic_number: 17,
            atomic_weight: 35.4527,
                  density: "1.56 (@ -33.6degC)",
            melting_point: -100.95,
            boiling_point: -34.55,
            atomic_radius: nil,
          covalent_radius: "99",
             ionic_radius: nil,
          specific_volume: 18.7,
            specific_heat: "0.477 (Cl-Cl)",
              heat_fusion: "6.41 (Cl-Cl)",
         heat_evaporation: "20.41 (Cl-Cl)",
     thermal_conductivity: "0.009",
pauling_electronegativity: 3.16,
  first_ionisation_energy: "1254.9",
         oxidation_states: "7 5 3 1 -1",
 electronic_configuration: "[Ne]3s²3p",
                  lattice: "ORC",
         lattice_constant: 6.24,
                 category: "halogens",
                   number: 17
)
Element.create(
                     name: "Bromine",
                   symbol: "Br",
            atomic_number: 35,
            atomic_weight: 79.904,
                  density: "3.12",
            melting_point: -7.25,
            boiling_point: 58.75,
            atomic_radius: nil,
          covalent_radius: "114",
             ionic_radius: nil,
          specific_volume: 23.5,
            specific_heat: "0.473 (Br-Br)",
              heat_fusion: "10.57 (Br-Br)",
         heat_evaporation: "29.56 (Br-Br)",
     thermal_conductivity: "0.005",
pauling_electronegativity: 2.96,
  first_ionisation_energy: "1142",
         oxidation_states: "7 5 3 1 -1",
 electronic_configuration: "[Ar]3d¹4s²4p",
                  lattice: "ORC",
         lattice_constant: 6.67,
                 category: "halogens",
                   number: 35
)
Element.create(
                     name: "Helium",
                   symbol: "He",
            atomic_number: 2,
            atomic_weight: 4.002602,
                  density: "0.147 (@ -270degC)",
            melting_point: -272.2,
            boiling_point: -268.934,
            atomic_radius: 0,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 31.8,
            specific_heat: "5.188",
              heat_fusion: nil,
         heat_evaporation: "0.08",
     thermal_conductivity: "0.152",
pauling_electronegativity: nil,
  first_ionisation_energy: "2361.3",
         oxidation_states: nil,
 electronic_configuration: "1s²",
                  lattice: "HEX",
         lattice_constant: 3.57,
                 category: "noble gases",
                   number: 2
)
Element.create(
                     name: "Neon",
                   symbol: "Ne",
            atomic_number: 10,
            atomic_weight: 20.1797,
                  density: "1.204 (@ -246degC)",
            melting_point: -225.15,
            boiling_point: -246.05,
            atomic_radius: nil,
          covalent_radius: "71",
             ionic_radius: nil,
          specific_volume: 16.8,
            specific_heat: "1.029",
              heat_fusion: nil,
         heat_evaporation: "1.74",
     thermal_conductivity: "<0.0493>",
pauling_electronegativity: 0,
  first_ionisation_energy: "2079.4",
         oxidation_states: nil,
 electronic_configuration: "[He]2s²2p",
                  lattice: "FCC",
         lattice_constant: 4.43,
                 category: "noble gases",
                   number: 10
)
Element.create(
                     name: "Argon",
                   symbol: "Ar",
            atomic_number: 18,
            atomic_weight: 39.948,
                  density: "1.40 (@ -186degC)",
            melting_point: -189.35,
            boiling_point: -185.85,
            atomic_radius: nil,
          covalent_radius: "98",
             ionic_radius: nil,
          specific_volume: 24.2,
            specific_heat: "0.138",
              heat_fusion: nil,
         heat_evaporation: "6.52",
     thermal_conductivity: "0.0177",
pauling_electronegativity: 0,
  first_ionisation_energy: "1519.6",
         oxidation_states: nil,
 electronic_configuration: "[Ne]3s²3p",
                  lattice: "FCC",
         lattice_constant: 5.26,
                 category: "noble gases",
                   number: 18
)
Element.create(
                     name: "Krypton",
                   symbol: "Kr",
            atomic_number: 36,
            atomic_weight: 83.8,
                  density: "2.155 (@ -153degC)",
            melting_point: -156.55,
            boiling_point: -152.3,
            atomic_radius: nil,
          covalent_radius: "112",
             ionic_radius: nil,
          specific_volume: 32.2,
            specific_heat: "0.247",
              heat_fusion: nil,
         heat_evaporation: "9.05",
     thermal_conductivity: "0.0095",
pauling_electronegativity: 0,
  first_ionisation_energy: "1350",
         oxidation_states: "2",
 electronic_configuration: "[Ar]3d¹4s²4p",
                  lattice: "FCC",
         lattice_constant: 5.72,
                 category: "noble gases",
                   number: 36
)
Element.create(
                     name: "Scandium",
                   symbol: "Sc",
            atomic_number: 21,
            atomic_weight: 44.95591,
                  density: "2.99",
            melting_point: 1540.85,
            boiling_point: 2830.85,
            atomic_radius: 162,
          covalent_radius: "144",
             ionic_radius: nil,
          specific_volume: 15,
            specific_heat: "0.556",
              heat_fusion: "15.8",
         heat_evaporation: "332.7",
     thermal_conductivity: "15.8",
pauling_electronegativity: 1.36,
  first_ionisation_energy: "630.8",
         oxidation_states: "3",
 electronic_configuration: "[Ar]3d¹4s²",
                  lattice: "HEX",
         lattice_constant: 3.31,
                 category: "transition elements",
                   number: 21
)
Element.create(
                     name: "Titanium",
                   symbol: "Ti",
            atomic_number: 22,
            atomic_weight: 47.88,
                  density: "4.54",
            melting_point: 1659.85,
            boiling_point: 3286.85,
            atomic_radius: 147,
          covalent_radius: "132",
             ionic_radius: nil,
          specific_volume: 10.6,
            specific_heat: "0.523",
              heat_fusion: "18.8",
         heat_evaporation: "422.6",
     thermal_conductivity: "21.9",
pauling_electronegativity: 1.54,
  first_ionisation_energy: "657.8",
         oxidation_states: "4 3",
 electronic_configuration: "[Ar]3d²4s²",
                  lattice: "HEX",
         lattice_constant: 2.95,
                 category: "transition elements",
                   number: 22
)
Element.create(
                     name: "Vanadium",
                   symbol: "V",
            atomic_number: 23,
            atomic_weight: 50.9415,
                  density: "6.11",
            melting_point: 1886.85,
            boiling_point: 3376.85,
            atomic_radius: 134,
          covalent_radius: "122",
             ionic_radius: nil,
          specific_volume: 8.35,
            specific_heat: "0.485",
              heat_fusion: "17.5",
         heat_evaporation: "460",
     thermal_conductivity: "30.7",
pauling_electronegativity: 1.63,
  first_ionisation_energy: "650.1",
         oxidation_states: "5 4 3 2 0",
 electronic_configuration: "[Ar]3d³4s²",
                  lattice: "BCC",
         lattice_constant: 3.02,
                 category: "transition elements",
                   number: 23
)
Element.create(
                     name: "Chromium",
                   symbol: "Cr",
            atomic_number: 24,
            atomic_weight: 51.9961,
                  density: "7.18",
            melting_point: 1856.85,
            boiling_point: 2671.85,
            atomic_radius: 130,
          covalent_radius: "118",
             ionic_radius: nil,
          specific_volume: 7.23,
            specific_heat: "0.488",
              heat_fusion: "21",
         heat_evaporation: "342",
     thermal_conductivity: "93.9",
pauling_electronegativity: 1.66,
  first_ionisation_energy: "652.4",
         oxidation_states: "6 3 2 0",
 electronic_configuration: "[Ar]3d4s¹",
                  lattice: "BCC",
         lattice_constant: 2.88,
                 category: "transition elements",
                   number: 24
)
Element.create(
                     name: "Iron",
                   symbol: "Fe",
            atomic_number: 26,
            atomic_weight: 55.847,
                  density: "7.874",
            melting_point: 1534.85,
            boiling_point: 2749.85,
            atomic_radius: 126,
          covalent_radius: "117",
             ionic_radius: nil,
          specific_volume: 7.1,
            specific_heat: "0.443",
              heat_fusion: "13.8",
         heat_evaporation: "~340",
     thermal_conductivity: "80.4",
pauling_electronegativity: 1.83,
  first_ionisation_energy: "759.1",
         oxidation_states: "6 3 2 0 -2",
 electronic_configuration: "[Ar]3d4s²",
                  lattice: "BCC",
         lattice_constant: 2.87,
                 category: "transition elements",
                   number: 26
)
Element.create(
                     name: "Neptunium",
                   symbol: "Np",
            atomic_number: 93,
            atomic_weight: 237.048,
                  density: "20.25",
            melting_point: 639.85,
            boiling_point: 3901.85,
            atomic_radius: 130,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 21.1,
            specific_heat: nil,
              heat_fusion: "-9.6",
         heat_evaporation: "336",
     thermal_conductivity: "<6.3>",
pauling_electronegativity: 1.36,
  first_ionisation_energy: "nil",
         oxidation_states: "6 5 4 3",
 electronic_configuration: "[Rn]5f6d¹7s²",
                  lattice: "ORC",
         lattice_constant: 4.72,
                 category: "actinides",
                   number: 93
)
Element.create(
                     name: "Plutonium",
                   symbol: "Pu",
            atomic_number: 94,
            atomic_weight: 244.0642,
                  density: "19.84",
            melting_point: 640.85,
            boiling_point: 3231.85,
            atomic_radius: 151,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: "2.8",
         heat_evaporation: "343.5",
     thermal_conductivity: "<6.7>",
pauling_electronegativity: 1.28,
  first_ionisation_energy: "491.9",
         oxidation_states: "6 5 4 3",
 electronic_configuration: "[Rn]5f6d7s²",
                  lattice: "MCL",
         lattice_constant: nil,
                 category: "actinides",
                   number: 94
)
Element.create(
                     name: "Americium",
                   symbol: "Am",
            atomic_number: 95,
            atomic_weight: 243.0614,
                  density: "13.67",
            melting_point: 993.85,
            boiling_point: 2606.85,
            atomic_radius: 173,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 20.8,
            specific_heat: nil,
              heat_fusion: "-10",
         heat_evaporation: "238.5",
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "nil",
         oxidation_states: "6 5 4 3",
 electronic_configuration: "[Rn]5f6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 95
)
Element.create(
                     name: "Palladium",
                   symbol: "Pd",
            atomic_number: 46,
            atomic_weight: 106.42,
                  density: "12.02",
            melting_point: 1551.85,
            boiling_point: 3139.85,
            atomic_radius: 137,
          covalent_radius: "128",
             ionic_radius: nil,
          specific_volume: 8.9,
            specific_heat: "0.244",
              heat_fusion: "17.24",
         heat_evaporation: "372.4",
     thermal_conductivity: "71.8",
pauling_electronegativity: 2.2,
  first_ionisation_energy: "803.5",
         oxidation_states: "4 2 0",
 electronic_configuration: "[Kr]4d5s",
                  lattice: "FCC",
         lattice_constant: 3.89,
                 category: "transition elements",
                   number: 46
)
Element.create(
                     name: "Silver",
                   symbol: "Ag",
            atomic_number: 47,
            atomic_weight: 107.8682,
                  density: "10.5",
            melting_point: 961.95,
            boiling_point: 2211.85,
            atomic_radius: 144,
          covalent_radius: "134",
             ionic_radius: nil,
          specific_volume: 10.3,
            specific_heat: "0.237",
              heat_fusion: "11.95",
         heat_evaporation: "254.1",
     thermal_conductivity: "429",
pauling_electronegativity: 1.93,
  first_ionisation_energy: "730.5",
         oxidation_states: "2 1",
 electronic_configuration: "[Kr]4d5s¹",
                  lattice: "FCC",
         lattice_constant: 4.09,
                 category: "transition elements",
                   number: 47
)
Element.create(
                     name: "Cadmium",
                   symbol: "Cd",
            atomic_number: 48,
            atomic_weight: 112.411,
                  density: "8.65",
            melting_point: 320.95,
            boiling_point: 764.85,
            atomic_radius: 154,
          covalent_radius: "148",
             ionic_radius: nil,
          specific_volume: 13.1,
            specific_heat: "0.232",
              heat_fusion: "6.11",
         heat_evaporation: "59.1",
     thermal_conductivity: "96.9",
pauling_electronegativity: 1.69,
  first_ionisation_energy: "867.2",
         oxidation_states: "2",
 electronic_configuration: "[Kr]4d5s²",
                  lattice: "HEX",
         lattice_constant: 2.98,
                 category: "transition elements",
                   number: 48
)
Element.create(
                     name: "Hafnium",
                   symbol: "Hf",
            atomic_number: 72,
            atomic_weight: 178.49,
                  density: "13.31",
            melting_point: 2229.85,
            boiling_point: 5196.85,
            atomic_radius: 167,
          covalent_radius: "144",
             ionic_radius: nil,
          specific_volume: 13.6,
            specific_heat: "0.146",
              heat_fusion: "-25.1",
         heat_evaporation: "575",
     thermal_conductivity: "23",
pauling_electronegativity: 1.3,
  first_ionisation_energy: "575.2",
         oxidation_states: "4",
 electronic_configuration: "[Xe]4f¹5d²6s²",
                  lattice: "HEX",
         lattice_constant: 3.2,
                 category: "transition elements",
                   number: 72
)
Element.create(
                     name: "Tantalum",
                   symbol: "Ta",
            atomic_number: 73,
            atomic_weight: 180.9479,
                  density: "16.654",
            melting_point: 2995.85,
            boiling_point: 5424.85,
            atomic_radius: 149,
          covalent_radius: "134",
             ionic_radius: nil,
          specific_volume: 10.9,
            specific_heat: "0.14",
              heat_fusion: "24.7",
         heat_evaporation: "758",
     thermal_conductivity: "57.5",
pauling_electronegativity: 1.5,
  first_ionisation_energy: "760.1",
         oxidation_states: "5",
 electronic_configuration: "[Xe]4f¹5d³6s²",
                  lattice: "BCC",
         lattice_constant: 3.31,
                 category: "transition elements",
                   number: 73
)
Element.create(
                     name: "Tungsten",
                   symbol: "W",
            atomic_number: 74,
            atomic_weight: 183.84,
                  density: "19.3",
            melting_point: 3406.85,
            boiling_point: 5656.85,
            atomic_radius: 141,
          covalent_radius: "130",
             ionic_radius: nil,
          specific_volume: 9.53,
            specific_heat: "0.133",
              heat_fusion: "-35",
         heat_evaporation: "824",
     thermal_conductivity: "173",
pauling_electronegativity: 1.7,
  first_ionisation_energy: "769.7",
         oxidation_states: "6 5 4 3 2 0",
 electronic_configuration: "[Xe]4f¹5d6s²",
                  lattice: "BCC",
         lattice_constant: 3.16,
                 category: "transition elements",
                   number: 74
)
Element.create(
                     name: "Francium",
                   symbol: "Fr",
            atomic_number: 87,
            atomic_weight: 223.0197,
                  density: nil,
            melting_point: 26.85,
            boiling_point: 676.85,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: "15",
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 0.7,
  first_ionisation_energy: "~375",
         oxidation_states: "2",
 electronic_configuration: "[Rn]7s¹",
                  lattice: "BCC",
         lattice_constant: nil,
                 category: "alkali metals",
                   number: 87
)
Element.create(
                     name: "Tin",
                   symbol: "Sn",
            atomic_number: 50,
            atomic_weight: 118.71,
                  density: "7.31",
            melting_point: 231.95,
            boiling_point: 2269.85,
            atomic_radius: 162,
          covalent_radius: "141",
             ionic_radius: nil,
          specific_volume: 16.3,
            specific_heat: "0.222",
              heat_fusion: "7.07",
         heat_evaporation: "296",
     thermal_conductivity: "66.8",
pauling_electronegativity: 1.96,
  first_ionisation_energy: "708.2",
         oxidation_states: "4 2",
 electronic_configuration: "[Kr]4d5s²5p²",
                  lattice: "TET",
         lattice_constant: 5.82,
                 category: "other metals",
                   number: 50
)
Element.create(
                     name: "Thallium",
                   symbol: "Tl",
            atomic_number: 81,
            atomic_weight: 204.3833,
                  density: "11.85",
            melting_point: 303.45,
            boiling_point: 1456.85,
            atomic_radius: 171,
          covalent_radius: "148",
             ionic_radius: nil,
          specific_volume: 17.2,
            specific_heat: "0.128",
              heat_fusion: "4.31",
         heat_evaporation: "162.4",
     thermal_conductivity: "46.1",
pauling_electronegativity: 1.62,
  first_ionisation_energy: "588.9",
         oxidation_states: "3 1",
 electronic_configuration: "[Xe]4f¹5d¹6s²6p¹",
                  lattice: "HEX",
         lattice_constant: 3.46,
                 category: "other metals",
                   number: 81
)
Element.create(
                     name: "Lead",
                   symbol: "Pb",
            atomic_number: 82,
            atomic_weight: 207.2,
                  density: "11.35",
            melting_point: 327.5,
            boiling_point: 1739.85,
            atomic_radius: 175,
          covalent_radius: "147",
             ionic_radius: nil,
          specific_volume: 18.3,
            specific_heat: "0.159",
              heat_fusion: "4.77",
         heat_evaporation: "177.8",
     thermal_conductivity: "35.3",
pauling_electronegativity: 1.8,
  first_ionisation_energy: "715.2",
         oxidation_states: "4 2",
 electronic_configuration: "[Xe]4f¹5d¹6s²6p²",
                  lattice: "FCC",
         lattice_constant: 4.95,
                 category: "other metals",
                   number: 82
)
Element.create(
                     name: "Bismuth",
                   symbol: "Bi",
            atomic_number: 83,
            atomic_weight: 208.98037,
                  density: "9.747",
            melting_point: 271.35,
            boiling_point: 1609.85,
            atomic_radius: 170,
          covalent_radius: "146",
             ionic_radius: nil,
          specific_volume: 21.3,
            specific_heat: "0.124",
              heat_fusion: "11",
         heat_evaporation: "172",
     thermal_conductivity: "7.9",
pauling_electronegativity: 2.02,
  first_ionisation_energy: "702.9",
         oxidation_states: "5 3",
 electronic_configuration: "[Xe]4f¹5d¹6s²6p³",
                  lattice: "RHL",
         lattice_constant: 4.75,
                 category: "other metals",
                   number: 83
)
Element.create(
                     name: "Promethium",
                   symbol: "Pm",
            atomic_number: 61,
            atomic_weight: 144.9127,
                  density: "7.2",
            melting_point: 1167.85,
            boiling_point: 2726.85,
            atomic_radius: nil,
          covalent_radius: "163",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: "0.185",
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: "17.9",
pauling_electronegativity: 0,
  first_ionisation_energy: "536",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f5d6s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "lanthanides",
                   number: 61
)
Element.create(
                     name: "Samarium",
                   symbol: "Sm",
            atomic_number: 62,
            atomic_weight: 150.36,
                  density: "7.52",
            melting_point: 1076.85,
            boiling_point: 1790.85,
            atomic_radius: 181,
          covalent_radius: "162",
             ionic_radius: nil,
          specific_volume: 19.9,
            specific_heat: "0.18",
              heat_fusion: "8.9",
         heat_evaporation: "165",
     thermal_conductivity: "<13.3>",
pauling_electronegativity: 1.17,
  first_ionisation_energy: "540.1",
         oxidation_states: "3 2",
 electronic_configuration: "[Xe]4f5d6s²",
                  lattice: "RHL",
         lattice_constant: 9,
                 category: "lanthanides",
                   number: 62
)
Element.create(
                     name: "Europium",
                   symbol: "Eu",
            atomic_number: 63,
            atomic_weight: 151.965,
                  density: "5.243",
            melting_point: 821.85,
            boiling_point: 1596.85,
            atomic_radius: 199,
          covalent_radius: "185",
             ionic_radius: nil,
          specific_volume: 28.9,
            specific_heat: "0.176",
              heat_fusion: nil,
         heat_evaporation: "176",
     thermal_conductivity: "13.9",
pauling_electronegativity: 0,
  first_ionisation_energy: "546.9",
         oxidation_states: "3 2",
 electronic_configuration: "[Xe]4f5d6s²",
                  lattice: "BCC",
         lattice_constant: 4.61,
                 category: "lanthanides",
                   number: 63
)
Element.create(
                     name: "Gadolinium",
                   symbol: "Gd",
            atomic_number: 64,
            atomic_weight: 157.25,
                  density: "7.9",
            melting_point: 1312.85,
            boiling_point: 3265.85,
            atomic_radius: 179,
          covalent_radius: "161",
             ionic_radius: nil,
          specific_volume: 19.9,
            specific_heat: "0.23",
              heat_fusion: nil,
         heat_evaporation: "398",
     thermal_conductivity: "<10.5>",
pauling_electronegativity: 1.2,
  first_ionisation_energy: "594.2",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f5d¹6s²",
                  lattice: "HEX",
         lattice_constant: 3.64,
                 category: "lanthanides",
                   number: 64
)
Element.create(
                     name: "Terbium",
                   symbol: "Tb",
            atomic_number: 65,
            atomic_weight: 158.92534,
                  density: "8.229",
            melting_point: 1355.85,
            boiling_point: 3022.85,
            atomic_radius: 180,
          covalent_radius: "159",
             ionic_radius: nil,
          specific_volume: 19.2,
            specific_heat: "0.183",
              heat_fusion: nil,
         heat_evaporation: "389",
     thermal_conductivity: "11.1",
pauling_electronegativity: 1.2,
  first_ionisation_energy: "569",
         oxidation_states: "4 3",
 electronic_configuration: "[Xe]4f5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.6,
                 category: "lanthanides",
                   number: 65
)
Element.create(
                     name: "Dysprosium",
                   symbol: "Dy",
            atomic_number: 66,
            atomic_weight: 162.5,
                  density: "8.55",
            melting_point: 1411.85,
            boiling_point: 2561.85,
            atomic_radius: 180,
          covalent_radius: "159",
             ionic_radius: nil,
          specific_volume: 19,
            specific_heat: "0.173",
              heat_fusion: nil,
         heat_evaporation: "291",
     thermal_conductivity: "10.7",
pauling_electronegativity: nil,
  first_ionisation_energy: "567",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.59,
                 category: "lanthanides",
                   number: 66
)
Element.create(
                     name: "Holmium",
                   symbol: "Ho",
            atomic_number: 67,
            atomic_weight: 164.93032,
                  density: "8.795",
            melting_point: 1473.85,
            boiling_point: 2694.85,
            atomic_radius: 179,
          covalent_radius: "158",
             ionic_radius: nil,
          specific_volume: 18.7,
            specific_heat: "0.164",
              heat_fusion: nil,
         heat_evaporation: "301",
     thermal_conductivity: "<16.2>",
pauling_electronegativity: 1.23,
  first_ionisation_energy: "574",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f¹¹5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.58,
                 category: "lanthanides",
                   number: 67
)
Element.create(
                     name: "Erbium",
                   symbol: "Er",
            atomic_number: 68,
            atomic_weight: 167.26,
                  density: "9.06",
            melting_point: 1528.85,
            boiling_point: 2862.85,
            atomic_radius: 178,
          covalent_radius: "157",
             ionic_radius: nil,
          specific_volume: 18.4,
            specific_heat: "0.168",
              heat_fusion: nil,
         heat_evaporation: "317",
     thermal_conductivity: "<14.5>",
pauling_electronegativity: 1.24,
  first_ionisation_energy: "581",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f¹²5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.56,
                 category: "lanthanides",
                   number: 68
)
Element.create(
                     name: "Thulium",
                   symbol: "Tm",
            atomic_number: 69,
            atomic_weight: 168.93421,
                  density: "9.321",
            melting_point: 1544.85,
            boiling_point: 1946.85,
            atomic_radius: 177,
          covalent_radius: "156",
             ionic_radius: nil,
          specific_volume: 18.1,
            specific_heat: "0.16",
              heat_fusion: nil,
         heat_evaporation: "232",
     thermal_conductivity: "<16.9>",
pauling_electronegativity: 1.25,
  first_ionisation_energy: "589",
         oxidation_states: "3 2",
 electronic_configuration: "[Xe]4f¹³5d6s²",
                  lattice: "HEX",
         lattice_constant: 3.54,
                 category: "lanthanides",
                   number: 69
)
Element.create(
                     name: "Ytterbium",
                   symbol: "Yb",
            atomic_number: 70,
            atomic_weight: 173.04,
                  density: "6.9654",
            melting_point: 823.85,
            boiling_point: 1192.85,
            atomic_radius: 194,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 24.8,
            specific_heat: "0.145",
              heat_fusion: "3.35",
         heat_evaporation: "159",
     thermal_conductivity: "<34.9>",
pauling_electronegativity: 1.1,
  first_ionisation_energy: "603",
         oxidation_states: "3 2",
 electronic_configuration: "[Xe]4f¹5d¹6s²",
                  lattice: "FCC",
         lattice_constant: 5.49,
                 category: "lanthanides",
                   number: 70
)
Element.create(
                     name: "Lutetium",
                   symbol: "Lu",
            atomic_number: 71,
            atomic_weight: 174.967,
                  density: "9.8404",
            melting_point: 1662.85,
            boiling_point: 3394.85,
            atomic_radius: 175,
          covalent_radius: "156",
             ionic_radius: nil,
          specific_volume: 17.8,
            specific_heat: "0.155",
              heat_fusion: nil,
         heat_evaporation: "414",
     thermal_conductivity: "<16.4>",
pauling_electronegativity: 1.27,
  first_ionisation_energy: "513",
         oxidation_states: "3",
 electronic_configuration: "[Xe]4f¹5d¹6s²",
                  lattice: "HEX",
         lattice_constant: 3.51,
                 category: "lanthanides",
                   number: 71
)
Element.create(
                     name: "Curium",
                   symbol: "Cm",
            atomic_number: 96,
            atomic_weight: 247.0703,
                  density: "13.51",
            melting_point: 1066.85,
            boiling_point: nil,
            atomic_radius: 299,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: 18.28,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<580>",
         oxidation_states: "4 3",
 electronic_configuration: "[Rn]5f6d¹7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 96
)
Element.create(
                     name: "Berkelium",
                   symbol: "Bk",
            atomic_number: 97,
            atomic_weight: 247.0703,
                  density: "13.25",
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: 297,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<600>",
         oxidation_states: "4 3",
 electronic_configuration: "[Rn]5f6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 97
)
Element.create(
                     name: "Californium",
                   symbol: "Cf",
            atomic_number: 98,
            atomic_weight: 251.0796,
                  density: "15.1",
            melting_point: 626.85,
            boiling_point: nil,
            atomic_radius: 295,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<610>",
         oxidation_states: "4 3",
 electronic_configuration: "[Rn]5f¹6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 98
)
Element.create(
                     name: "Einsteinium",
                   symbol: "Es",
            atomic_number: 99,
            atomic_weight: 252.083,
                  density: nil,
            melting_point: nil,
            boiling_point: 856.85,
            atomic_radius: 292,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<620>",
         oxidation_states: "3",
 electronic_configuration: "[Rn]5f¹¹6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 99
)
Element.create(
                     name: "Fermium",
                   symbol: "Fm",
            atomic_number: 100,
            atomic_weight: 257.0951,
                  density: nil,
            melting_point: 1526.85,
            boiling_point: nil,
            atomic_radius: 290,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<630>",
         oxidation_states: "3",
 electronic_configuration: "[Rn]5f¹²6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 100
)
Element.create(
                     name: "Mendelevium",
                   symbol: "Md",
            atomic_number: 101,
            atomic_weight: 258.1,
                  density: nil,
            melting_point: 826.85,
            boiling_point: nil,
            atomic_radius: 287,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<635>",
         oxidation_states: "3",
 electronic_configuration: "[Rn]5f¹³6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 101
)
Element.create(
                     name: "Nobelium",
                   symbol: "No",
            atomic_number: 102,
            atomic_weight: 259.1009,
                  density: nil,
            melting_point: 826.85,
            boiling_point: nil,
            atomic_radius: 285,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: 1.3,
  first_ionisation_energy: "<640>",
         oxidation_states: "32",
 electronic_configuration: "[Rn]5f¹6d7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 102
)
Element.create(
                     name: "Lawrencium",
                   symbol: "Lr",
            atomic_number: 103,
            atomic_weight: 262.11,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: 282,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: "3",
 electronic_configuration: "[Rn]5f¹6d¹7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "actinides",
                   number: 103
)
Element.create(
                     name: "Manganese",
                   symbol: "Mn",
            atomic_number: 25,
            atomic_weight: 54.93805,
                  density: "7.21",
            melting_point: 1243.85,
            boiling_point: 1961.85,
            atomic_radius: 135,
          covalent_radius: "117",
             ionic_radius: nil,
          specific_volume: 7.39,
            specific_heat: "0.477",
              heat_fusion: "-13.4",
         heat_evaporation: "221",
     thermal_conductivity: "<7.8>",
pauling_electronegativity: 1.55,
  first_ionisation_energy: "716.8",
         oxidation_states: "7 6 4 3 2 0 -1",
 electronic_configuration: "[Ar]3d4s²",
                  lattice: "CUB",
         lattice_constant: 8.89,
                 category: "transition elements",
                   number: 25
)
Element.create(
                     name: "Cobalt",
                   symbol: "Co",
            atomic_number: 27,
            atomic_weight: 58.9332,
                  density: "8.9",
            melting_point: 1494.85,
            boiling_point: 2869.85,
            atomic_radius: 125,
          covalent_radius: "116",
             ionic_radius: nil,
          specific_volume: 6.7,
            specific_heat: "0.456",
              heat_fusion: "15.48",
         heat_evaporation: "389.1",
     thermal_conductivity: "100",
pauling_electronegativity: 1.88,
  first_ionisation_energy: "758.1",
         oxidation_states: "3 2 0 -1",
 electronic_configuration: "[Ar]3d4s²",
                  lattice: "HEX",
         lattice_constant: 2.51,
                 category: "transition elements",
                   number: 27
)
Element.create(
                     name: "Nickel",
                   symbol: "Ni",
            atomic_number: 28,
            atomic_weight: 58.6934,
                  density: "8.902",
            melting_point: 1452.85,
            boiling_point: 2731.85,
            atomic_radius: 124,
          covalent_radius: "115",
             ionic_radius: nil,
          specific_volume: 6.6,
            specific_heat: "0.443",
              heat_fusion: "17.61",
         heat_evaporation: "378.6",
     thermal_conductivity: "90.9",
pauling_electronegativity: 1.91,
  first_ionisation_energy: "736.2",
         oxidation_states: "3 2 0",
 electronic_configuration: "[Ar]3d4s²",
                  lattice: "FCC",
         lattice_constant: 3.52,
                 category: "transition elements",
                   number: 28
)
Element.create(
                     name: "Copper",
                   symbol: "Cu",
            atomic_number: 29,
            atomic_weight: 63.546,
                  density: "8.96",
            melting_point: 1083.45,
            boiling_point: 2566.85,
            atomic_radius: 128,
          covalent_radius: "117",
             ionic_radius: nil,
          specific_volume: 7.1,
            specific_heat: "0.385",
              heat_fusion: "13.01",
         heat_evaporation: "304.6",
     thermal_conductivity: "401",
pauling_electronegativity: 1.9,
  first_ionisation_energy: "745",
         oxidation_states: "2 1",
 electronic_configuration: "[Ar]3d¹4s¹",
                  lattice: "FCC",
         lattice_constant: 3.61,
                 category: "transition elements",
                   number: 29
)
Element.create(
                     name: "Zinc",
                   symbol: "Zn",
            atomic_number: 30,
            atomic_weight: 65.39,
                  density: "7.133",
            melting_point: 419.58,
            boiling_point: 906.85,
            atomic_radius: 138,
          covalent_radius: "125",
             ionic_radius: nil,
          specific_volume: 9.2,
            specific_heat: "0.388",
              heat_fusion: "7.28",
         heat_evaporation: "114.8",
     thermal_conductivity: "116",
pauling_electronegativity: 1.65,
  first_ionisation_energy: "905.8",
         oxidation_states: "2",
 electronic_configuration: "[Ar]3d¹4s²",
                  lattice: "HEX",
         lattice_constant: 2.66,
                 category: "transition elements",
                   number: 30
)
Element.create(
                     name: "Yttrium",
                   symbol: "Y",
            atomic_number: 39,
            atomic_weight: 88.90585,
                  density: "4.47",
            melting_point: 1521.85,
            boiling_point: 3337.85,
            atomic_radius: 178,
          covalent_radius: "162",
             ionic_radius: nil,
          specific_volume: 19.8,
            specific_heat: "0.284",
              heat_fusion: "11.5",
         heat_evaporation: "367",
     thermal_conductivity: "<17.2>",
pauling_electronegativity: 1.22,
  first_ionisation_energy: "615.4",
         oxidation_states: "3",
 electronic_configuration: "[Kr]4d¹5s²",
                  lattice: "HEX",
         lattice_constant: 3.65,
                 category: "transition elements",
                   number: 39
)
Element.create(
                     name: "Zirconium",
                   symbol: "Zr",
            atomic_number: 40,
            atomic_weight: 91.224,
                  density: "6.506",
            melting_point: 1851.85,
            boiling_point: 4376.85,
            atomic_radius: 160,
          covalent_radius: "145",
             ionic_radius: nil,
          specific_volume: 14.1,
            specific_heat: "0.281",
              heat_fusion: "19.2",
         heat_evaporation: "567",
     thermal_conductivity: "22.7",
pauling_electronegativity: 1.33,
  first_ionisation_energy: "659.7",
         oxidation_states: "4",
 electronic_configuration: "[Kr]4d²5s²",
                  lattice: "HEX",
         lattice_constant: 3.23,
                 category: "transition elements",
                   number: 40
)
Element.create(
                     name: "Niobium",
                   symbol: "Nb",
            atomic_number: 41,
            atomic_weight: 92.90638,
                  density: "8.57",
            melting_point: 2467.85,
            boiling_point: 4741.85,
            atomic_radius: 146,
          covalent_radius: "134",
             ionic_radius: nil,
          specific_volume: 10.8,
            specific_heat: "0.268",
              heat_fusion: "26.8",
         heat_evaporation: "680",
     thermal_conductivity: "53.7",
pauling_electronegativity: 1.6,
  first_ionisation_energy: "663.6",
         oxidation_states: "5 3",
 electronic_configuration: "[Kr]4d5s¹",
                  lattice: "BCC",
         lattice_constant: 3.3,
                 category: "transition elements",
                   number: 41
)
Element.create(
                     name: "Molybdenum",
                   symbol: "Mo",
            atomic_number: 42,
            atomic_weight: 95.94,
                  density: "10.22",
            melting_point: 2616.85,
            boiling_point: 4611.85,
            atomic_radius: 139,
          covalent_radius: "130",
             ionic_radius: nil,
          specific_volume: 9.4,
            specific_heat: "0.251",
              heat_fusion: "28",
         heat_evaporation: "~590",
     thermal_conductivity: "<138>",
pauling_electronegativity: 2.16,
  first_ionisation_energy: "684.8",
         oxidation_states: "6 5 4 3 2 0",
 electronic_configuration: "[Kr]4d5s¹",
                  lattice: "BCC",
         lattice_constant: 3.15,
                 category: "transition elements",
                   number: 42
)
Element.create(
                     name: "Rutherfordium",
                   symbol: "Rf",
            atomic_number: 104,
            atomic_weight: 261,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: "[Rn]5f¹6d²7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 104
)
Element.create(
                     name: "Dubnium",
                   symbol: "Db",
            atomic_number: 105,
            atomic_weight: 262,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: "[Rn]5f¹6d³6s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 105
)
Element.create(
                     name: "Seaborgium",
                   symbol: "Sg",
            atomic_number: 106,
            atomic_weight: 266,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: "[Rn]5f¹6d¹7s²",
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 106
)
Element.create(
                     name: "Hassium",
                   symbol: "Hs",
            atomic_number: 108,
            atomic_weight: 269,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 108
)
Element.create(
                     name: "Meitnerium",
                   symbol: "Mt",
            atomic_number: 109,
            atomic_weight: 268,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 109
)
Element.create(
                     name: "Ununnilium",
                   symbol: "Uun",
            atomic_number: 110,
            atomic_weight: 269,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 110
)
Element.create(
                     name: "Unununium",
                   symbol: "Uuu",
            atomic_number: 111,
            atomic_weight: 272,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 111
)
Element.create(
                     name: "Ununbium",
                   symbol: "Uub",
            atomic_number: 112,
            atomic_weight: 277,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 112
)
Element.create(
                     name: "Ununtrium",
                   symbol: "Uut",
            atomic_number: 113,
            atomic_weight: nil,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 113
)
Element.create(
                     name: "Technetium",
                   symbol: "Tc",
            atomic_number: 43,
            atomic_weight: 97.9072,
                  density: "11.5",
            melting_point: 2171.85,
            boiling_point: 4876.85,
            atomic_radius: 136,
          covalent_radius: "127",
             ionic_radius: nil,
          specific_volume: 8.5,
            specific_heat: "0.243",
              heat_fusion: "23.8",
         heat_evaporation: "585",
     thermal_conductivity: "50.6",
pauling_electronegativity: 1.9,
  first_ionisation_energy: "702.2",
         oxidation_states: "7",
 electronic_configuration: "[Kr]4d5s¹",
                  lattice: "HEX",
         lattice_constant: 2.74,
                 category: "transition elements",
                   number: 43
)
Element.create(
                     name: "Ruthenium",
                   symbol: "Ru",
            atomic_number: 44,
            atomic_weight: 101.07,
                  density: "12.41",
            melting_point: 2309.85,
            boiling_point: 3899.85,
            atomic_radius: 134,
          covalent_radius: "125",
             ionic_radius: nil,
          specific_volume: 8.3,
            specific_heat: "0.238",
              heat_fusion: "<25.5>",
         heat_evaporation: nil,
     thermal_conductivity: "117",
pauling_electronegativity: 2.2,
  first_ionisation_energy: "710.3",
         oxidation_states: "8 6 4 3 2 0 -2",
 electronic_configuration: "[Kr]4d5s¹",
                  lattice: "HEX",
         lattice_constant: 2.7,
                 category: "transition elements",
                   number: 44
)
Element.create(
                     name: "Rhodium",
                   symbol: "Rh",
            atomic_number: 45,
            atomic_weight: 102.9055,
                  density: "12.41",
            melting_point: 1965.85,
            boiling_point: 3726.85,
            atomic_radius: 134,
          covalent_radius: "125",
             ionic_radius: nil,
          specific_volume: 8.3,
            specific_heat: "0.244",
              heat_fusion: "21.8",
         heat_evaporation: "494",
     thermal_conductivity: "150",
pauling_electronegativity: 2.28,
  first_ionisation_energy: "719.5",
         oxidation_states: "5 4 3 2 1 0",
 electronic_configuration: "[Kr]4d5s¹",
                  lattice: "FCC",
         lattice_constant: 3.8,
                 category: "transition elements",
                   number: 45
)
Element.create(
                     name: "Rhenium",
                   symbol: "Re",
            atomic_number: 75,
            atomic_weight: 186.207,
                  density: "21.02",
            melting_point: 3179.85,
            boiling_point: 5626.85,
            atomic_radius: 137,
          covalent_radius: "128",
             ionic_radius: nil,
          specific_volume: 8.85,
            specific_heat: "0.138",
              heat_fusion: "34",
         heat_evaporation: "704",
     thermal_conductivity: "48",
pauling_electronegativity: 1.9,
  first_ionisation_energy: "759.1",
         oxidation_states: "5 4 3 2 -1",
 electronic_configuration: "[Xe]4f¹5d6s²",
                  lattice: "HEX",
         lattice_constant: 2.76,
                 category: "transition elements",
                   number: 75
)
Element.create(
                     name: "Osmium",
                   symbol: "Os",
            atomic_number: 76,
            atomic_weight: 190.23,
                  density: "22.57",
            melting_point: 3053.85,
            boiling_point: 5026.85,
            atomic_radius: 135,
          covalent_radius: "126",
             ionic_radius: nil,
          specific_volume: 8.43,
            specific_heat: "0.131",
              heat_fusion: "31.7",
         heat_evaporation: "738",
     thermal_conductivity: "<87.6>",
pauling_electronegativity: 2.2,
  first_ionisation_energy: "819.8",
         oxidation_states: "8 6 4 3 2 0 -2",
 electronic_configuration: "[Xe]4f¹5d6s²",
                  lattice: "HEX",
         lattice_constant: 2.74,
                 category: "transition elements",
                   number: 76
)
Element.create(
                     name: "Iridium",
                   symbol: "Ir",
            atomic_number: 77,
            atomic_weight: 192.22,
                  density: "22.42",
            melting_point: 2409.85,
            boiling_point: 4129.85,
            atomic_radius: 136,
          covalent_radius: "127",
             ionic_radius: nil,
          specific_volume: 8.54,
            specific_heat: "0.133",
              heat_fusion: "27.61",
         heat_evaporation: "604",
     thermal_conductivity: "147",
pauling_electronegativity: 2.2,
  first_ionisation_energy: "868.1",
         oxidation_states: "6 4 3 2 1 0 -1",
 electronic_configuration: "[Xe]4f¹5d6s²",
                  lattice: "FCC",
         lattice_constant: 3.84,
                 category: "transition elements",
                   number: 77
)
Element.create(
                     name: "Platinum",
                   symbol: "Pt",
            atomic_number: 78,
            atomic_weight: 195.08,
                  density: "21.45",
            melting_point: 1771.85,
            boiling_point: 3826.85,
            atomic_radius: 139,
          covalent_radius: "130",
             ionic_radius: nil,
          specific_volume: 9.1,
            specific_heat: "0.133",
              heat_fusion: "21.76",
         heat_evaporation: "~470",
     thermal_conductivity: "71.6",
pauling_electronegativity: 2.28,
  first_ionisation_energy: "868.1",
         oxidation_states: "4 2 0",
 electronic_configuration: "[Xe]4f¹5d6s²",
                  lattice: "FCC",
         lattice_constant: 3.92,
                 category: "transition elements",
                   number: 78
)
Element.create(
                     name: "Gold",
                   symbol: "Au",
            atomic_number: 79,
            atomic_weight: 196.96654,
                  density: "19.3",
            melting_point: 1064.43,
            boiling_point: 2806.85,
            atomic_radius: 146,
          covalent_radius: "134",
             ionic_radius: nil,
          specific_volume: 10.2,
            specific_heat: "0.129",
              heat_fusion: "12.68",
         heat_evaporation: "~340",
     thermal_conductivity: "318",
pauling_electronegativity: 2.54,
  first_ionisation_energy: "889.3",
         oxidation_states: "3 1",
 electronic_configuration: "[Xe]4f¹5d¹6s²",
                  lattice: "FCC",
         lattice_constant: 4.08,
                 category: "transition elements",
                   number: 79
)
Element.create(
                     name: "Mercury",
                   symbol: "Hg",
            atomic_number: 80,
            atomic_weight: 200.59,
                  density: "13.546 (@ +20degC)",
            melting_point: -38.87,
            boiling_point: 356.58,
            atomic_radius: 157,
          covalent_radius: "149",
             ionic_radius: nil,
          specific_volume: 14.8,
            specific_heat: "0.138",
              heat_fusion: "2.295",
         heat_evaporation: "58.5",
     thermal_conductivity: "8.3",
pauling_electronegativity: 2,
  first_ionisation_energy: "1006",
         oxidation_states: "2 1",
 electronic_configuration: "[Xe]4f¹5d¹6s²",
                  lattice: "RHL",
         lattice_constant: 2.99,
                 category: "transition elements",
                   number: 80
)
Element.create(
                     name: "Ununquadium",
                   symbol: "Uuq",
            atomic_number: 114,
            atomic_weight: 289,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 114
)
Element.create(
                     name: "Ununpentium",
                   symbol: "Uup",
            atomic_number: 115,
            atomic_weight: nil,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 115
)
Element.create(
                     name: "Ununhexium",
                   symbol: "Uuh",
            atomic_number: 116,
            atomic_weight: nil,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 116
)
Element.create(
                     name: "Ununseptium",
                   symbol: "Uus",
            atomic_number: 117,
            atomic_weight: nil,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 117
)
Element.create(
                     name: "Ununoctium",
                   symbol: "Uuo",
            atomic_number: 118,
            atomic_weight: nil,
                  density: nil,
            melting_point: nil,
            boiling_point: nil,
            atomic_radius: nil,
          covalent_radius: "nil",
             ionic_radius: nil,
          specific_volume: nil,
            specific_heat: nil,
              heat_fusion: nil,
         heat_evaporation: nil,
     thermal_conductivity: nil,
pauling_electronegativity: nil,
  first_ionisation_energy: "nil",
         oxidation_states: nil,
 electronic_configuration: nil,
                  lattice: nil,
         lattice_constant: nil,
                 category: "transition elements",
                   number: 118
)
