Alum.create(first_name: "Olivia",  last_name: "Swayne",    class_year: 1952)
Alum.create(first_name: "Jacklyn", last_name: "Clifton",   class_year: 2010)
Alum.create(first_name: "Barbara", last_name: "Pass",      class_year: 1974)
Alum.create(first_name: "Kerry",   last_name: "Stafford",  class_year: 2010)
Alum.create(first_name: "Harvey",  last_name: "Sylvestre", class_year: 1974)
Alum.create(first_name: "Oliver",  last_name: "Goldsmith", class_year: 1952)
Alum.create(first_name: "Richard", last_name: "Matteo",    class_year: 1974)
