EncyclopediaEntry.create(
  word: "magpie",
  content: "MAGPIE, or simply PIE (Fr. pie), the prefix being the abbreviated form of a human name (Margaret'), a bird once common throughout Great Britain, though now nearly everywhere scarce. Its pilfering habits have led to this result, yet the injuries it causes are exaggerated by common report; and in many countries of Europe it is still the tolerated or even the cherished neighbour of every farmer, as it formerly was in England if not in Scotland also. It did not exist in Ireland in 1617, when Fynes Morison wrote his Itinerary, but it had appeared there within a hundred years later, when Swift mentions its occurrences in his Journal to Stella, 9th July 1711. It is now common enough in that country, and there is a widespread but unfounded belief that it was introduced by the English out of spite. It is a species that when not molested is extending its range, as J. Wolley ascertained in Lapland, where within the last century it has been gradually pushing its way along the coast and into the interior from one fishing-station or settler's house to the next, as the country has been peopled.")

EncyclopediaEntry.create(
  word: "sandpiper",
  content: "SANDPIPER (Ger. Sandpfeifer), the name applied to nearly all the smaller kinds of the group Limicolae which are not Plovers (q.v.) or Snipes (q.v.), but may be said to be intermediate between them. According to F. Willughby in 1676 it was the name given by Yorkshiremen to the bird popularly known in England as the \"Summer-Snipe,\" - the Tringa hypoleucos of Linnaeus and the Totanus hypoleucos of later writers, - but probably even in Willughby's time the name was of much wider signification. Placed by most systematists in the family Scolopacidae, the birds commonly called Sandpipers seem to form three sections, which have been often regarded as Subfamilies - Totaninae, Tringinae and Phalaropodinae, the last indeed in some classifications taking the higher rank of a Family - Phalaropodidae. This section comprehends three species only, known as Phalaropes or swimming sandpipers, which are distinguished by the membranes that fringe their toes, in two of the species forming marginal lobes,' and by the character of their lower plumage, which is as close as that of a duck. The most obvious distinctions between Totaninae and Tringinae may be said to lie in the acute or blunt form of the tip of the bill (with which is associated a less or greater development of the sensitive nerves running almost if not quite to its extremity, and therefore greatly influencing the mode of feeding) and in the style of plumage - the Tringinae, with blunt and flexible bills, mostly assuming a summer-dress in which some tint of chestnut or reddish-brown 1 These are Phalaropus fulicarius and P. (or Lobipes) hyperboreus, and were thought by some of the older writers to be allied to the Coots (q.v.). The third species is P. (or Steganopus) wilsoni. All are natives of the higher parts of the N. hemisphere, and the last is especially American, though perhaps a straggler to Europe.")

EncyclopediaEntry.create(
  word: "jay",
  content: "JAY (Fr. geai), a well-known and very beautiful European bird, the Corvus glandarius of Linnaeus, the Garrulus glandarius of modern ornithologists. To this species are more or less closely allied numerous birds inhabiting the Palaearctic and Indian regions, as well as the greater part of America, but not occurring in the Antilles, in the southern portion of the Neotropical Region, or in the Ethiopian or Australian. All these birds are commonly called jays, and form a group of the crows or Corvidae, which may fairly be considered a sub-family, Garrulinae. Indeed there are, or have been, systematists who would elevate the jays to the rank of a family Garrulidae - a proceeding which seems unnecessary. Some of them have an unquestionable resemblance to the pies, if the group now known by that name can be satisfactorily severed from the true Corvinae. In structure the jays are not readily differentiated from the pies; but in habit they are much more arboreal, delighting in thick coverts, seldom appearing in the open, and seeking their food on or under trees. They seem also never to walk or run when on the ground, but always to hop. The bodyfeathers are commonly loose and soft; and, gaily coloured as are most of the species, in few of them has the plumage the metallic glossiness it generally presents in the pies, while the proverbial beauty of the \"jay's wing\" is due to the vivid tints of blue - turquoise and cobalt, heightened by bars of jet-black, an indication of the same style of ornament being observable in the greater number of the other forms of the group, and in some predominating over nearly the whole surface. Of the many genera that have been proposed by ornithologists, perhaps about nine may be deemed sufficiently well established.")

EncyclopediaEntry.create(
  word: "albatross",
  content: "ALBATROSS (from the Port. Alcatraz, a pelican), the name of a genus of aquatic birds (Diomedea), closely allied to the petrels, and belonging, like them, to the order Tubinares. In the name Diomedea, assigned to them by Linnaeus, there is a reference to the mythical metamorphosis of the companions of the Greek warrior Diomedes into birds. The beak is large, strong and sharp-edged, the upper mandible terminating in a large hook; the wings are narrow and very long; the feet have no hind toe, and the three anterior toes are completely webbed. The best known is the common or wandering albatross (D. exulans), which occurs in all parts of the Southern Ocean. It is the largest and strongest of all sea-birds. The length of the body is stated at 4 ft., and the weight at from 15 to 25 lb. It sometimes measures as much as 17 ft. between the tips of the extended wings, averaging probably from Io to 12 ft. Its strength of wing is very great. It often accompanies a ship for days - not merely following it, but wheeling in wide circles round it - without ever being observed to alight on the water, and continues its flight, apparently untired, in tempestuous as well as in moderate weather. It has even been said to sleep on the wing, and Moore alludes to this fanciful \"cloudrocked slumbering\" in his Fire Worshippers. It feeds on small fish and on the animal refuse that floats on the sea, eating to such excess at times that it is unable to fly and rests helplessly on the water. The colour of the bird is white, the back being streaked transversely with black or brown bands, and the wings dark. Sailors capture the bird for its long wing-bones, which they manufacture into tobacco-pipe stems. The albatross lays one egg; it is white, with a few spots, and is about 4 in. long. In breeding-time the bird resorts to solitary island groups, like the Crozet Islands and the elevated Tristan da Cunha, where it has its nest - a natural hollow or a circle of earth roughly scraped together - on the open ground. The early explorers of the great Southern Sea cheered themselves with the companionship of the albatross in its dreary solitudes; and the evil hap of him who shot with his cross-bow the bird of good omen is familiar to readers of Coleridge's Rime of the Ancient Mariner. Several species of albatross are known; for the smaller forms see Mallemuck.");
